### ISSUE TITLE
Need to update readme

### ISSUE THREAD

**Issue by BenKaehler** [caporaso-lab/tax-credit-code#4]
Need to update readme to reflect the new arrangement.

**Comment by nbokulich** [comment]
fixed in #5

**Comment by devonorourke** [comment]
I couldn't get the code repo to install properly because the example script in the `README.md` file was using a differently-named repo. The example provided:

```
git clone https://github.com/gregcaporaso/tax-credit-code.git
cd tax-credit-code
pip install .
```

I'm pretty sure you want it to read:
```
git clone https://github.com/caporaso-lab/tax-credit-code.git
```

**Comment by nbokulich** [comment]
you're right, the repo ownership was changed. Will fix. Thanks!
